#!/usr/bin/env bash

# check docker image for building
if [ "$(docker images -q httpp:12.x 2> /dev/null)" == "" ]; then
  echo "Build Docker image as httpp:12.x"
  docker image build --compress -t httpp:12.x -f ./Dockerfile ./appins/
fi

# execute commands 
if [ $# -ne 0 ]; then
  echo "$@ ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t \
  --rm --network host \
  httpp:12.x $@
else
  echo "Start Node.js REPL ..."
  docker run -i -t \
  --rm  --network host \
  httpp:12.x
fi
