name: test-macOS

on:
  push:
    branches: [ v12.x-httpp ]
  pull_request:
    branches: [ v12.x-httpp ]

env:
  PYTHON_VERSION: 2.7
  FLAKY_TESTS: dontcare

jobs:
  test-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j8 V=1
      - name: Test
        run: make run-ci -j8 V=1 TEST_CI_ARGS="-p dots"
